### PR TITLE
Reactivation of browser autofill

### LINKED ISSUE #1534: Auto-fill pop-up menu doesn't appear when selecting or typing in an entry field
### Bromite version

Version: 94.0.4606.109
Arch: arm64
Android version: 12 beta 5
Device model: Pixel 3a

### Flags

These are the flags changed under `chrome://flags`:

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
Yes

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

### Describe the bug

auto-fill pop-up menu doesn't appear when selecting or typing in an entry field

### Steps to reproduce the bug

Steps to reproduce the bug:
1. go to https://fill.dev/form/identity-simple
2. select an entry field or start typing
3. the auto-fill pop-up menu does not appear
4. if you long-press the field, a pop-up menu will show 'paste' along with a three-dot button. clicking the button brings up 'auto-fill'. clicking it has no effect

Do not write "any website", specify which URLs can be used to reproduce the issue.

### Expected behavior

the corresponding auto-fill information appears in pop-up

### Screenshots

Screenshot_20211104-230545
- long-press entry field result

Screenshot_20211104-230551
- click on three-dot menu button result

Screenshot_20211104-230700
- correct behavior in chrome

### PR DESCRIPTION
**Pull request by uazo**
I modified the patch to reactivate the browser autofill management together with the native one.
Some functions are in fact managed by the internal chromium manager.

Fix for #1534

### CODE REVIEW

**Comment by csagan5** [comment]
I think the PR does not describe everything which is happening here: there are 2 new switches introduced?

**Comment by uazo** [comment]
you are right, because there are also changes related to #1590

**Review by csagan5 — CHANGES_REQUESTED** [review]
Please update the PR to describe what changes are being made; the patch description should also mention that.

**Comment by csagan5** [comment]
The conflict cannot be fixed by me:
```
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/enable-browser-autofill.
remote: error: At least 1 approving review is required by reviewers with write access.
```

However I have merged your patch and applied the changes I requested (to the patch description, PR description still does not mention the new toggle).

**Comment by uazo** [comment]
> remote: error: At least 1 approving review is required by reviewers with write access.

I'm sorry, but I just don't know how to fix it.
it would be easier perhaps if you allowed me to create branches directly in bromite.

**Comment by csagan5** [comment]
It is not a big deal, only some merges are missing.

> I'm sorry, but I just don't know how to fix it.

This error explains it: `At least 1 approving review is required by reviewers with write access.` You need to remove branch protection from branches which are not `master`.

If you fork from scratch it will also have the correct settings (or it used to have them).

> it would be easier perhaps if you allowed me to create branches directly in bromite.

That is not possible, I prefer to keep the security very strict.

**Comment by uazo** [comment]
> This error explains it: At least 1 approving review is required by reviewers with write access. You need to remove branch protection from branches which are not master

I am about to insert a new action on my fork to automatically check the git apply, maybe I will ask for help to configure the permissions correctly and then remove that protection.
the alternative is that you accept superpowers in my fork, I think I can trust :)

> That is not possible, I prefer to keep the security very strict.

my own motivation

**Pull request closed without merging**
