### PR TITLE
fix global "Autoplay" site-setting

### PR DESCRIPTION
**Pull request by uazo**
fix toggling on/off in Settings > Site Settings > Autoplay as written https://github.com/bromite/bromite/issues/791#issuecomment-733887208

### CODE REVIEW

**Comment by csagan5** [comment]
Great job!

**Comment by nikolowry** [comment]
Just ran `./bromite-builder --arch=arm64 --upstream` locally and wasn't able to apply this patch due to the trailing whitespace added by `Timezone-customization.patch` at https://github.com/bromite/bromite/blob/d446f0e453833d367348b869986bbed1254363f2/build/patches/Timezone-customization.patch#L1145

I was able to start building by removing the trailing whitespace from `Timezone-customization.patch`, adding the modified patch to a directory named `overrides` and then running: `./bromite-builder --arch=arm64 --patches=overrides --upstream`

**Comment by nikolowry** [comment]
I can confirm the updated patch is working as expected. Thanks again!

**Comment by uazo** [comment]
> wasn't able to apply this patch due to the trailing whitespace

it's true, I'm still a rookie in these things! only recently have I understood the importance of removing spaces ...

does anyone know any plugins for vscode that help me find these errors while developing? for now I solved it in another way, https://github.com/uazo/bromite-buildtools/blob/b34479fe9a150a63dd852eb1ba2f5d9d33bd887d/apply-single-patch.sh#L16 but I have to run the build twice and it takes too long for my taste.

@csagan5 could you make your script available to keep the timestamps of the files? thanks!

**Comment by uazo** [comment]
> https://github.com/nikolowry/bromite-builder/blob/a2d051bbc35be4da950a20c58a3fb5049af811a9/bromite-builder#L127
>
>        && fetch --nohooks android

@nikolowry if you want to improve fetch times, I recommend this change:

```
git fetch --depth 2 https://chromium.googlesource.com/chromium/src.git +refs/tags/$VERSION:chromium_$VERSION
gclient sync -D

```

**Comment by csagan5** [comment]
> @csagan5 could you make your script available to keep the timestamps of the files? thanks!

Sure; I will release it tomorrow.

**Comment by nikolowry** [comment]
@uazo @csagan5 my script was designed for applying small customizations on-top of release builds. I could add an option for using a local Bromite git folder instead of the release archives -- then it be easy for you to run `./bromite-builder prepare` to verify everything applies cleanly.

If either of you would find that helpful, I'll make the necessary changes. Just let me know.

**Comment by csagan5** [comment]
@uazo it is here: https://github.com/bromite/mtool

There is a script to show how to use it with Chromium.

**Comment by uazo** [comment]
> I could add an option for using a local Bromite git folder instead of the release archives

thanks @nikolowry but I think until we have a CI it doesn't make much sense. maybe in the future :)
my personal opinion, obviously carl decides here, maybe it would be useful instead and I don't know.

**Comment by nikolowry** [comment]
> thanks @nikolowry but I think until we have a CI it doesn't make much sense. maybe in the future :)

@uazo, running `./bromite-builder prepare --no-skip-patches` (with an option to use your local bromite working directory) would have alerted you to the trailing whitespace issue that I commented about earlier. Regardless of CI and/or future plans, it can be helpful now for verifying that patches are being cleanly applied to fresh builds.

> my personal opinion, obviously carl decides here, maybe it would be useful instead and I don't know.

`bromite-builder` is just a personal hobby project because I wanted some opinionated customizations (like a dark navbar) and also so I could have an excuse to work on different shell scripting patterns/techniques. However, I'll never hesitate on making changes or feature-additions if it can help you two in anyway.

---

Sidebar: @uazo I've been experimenting with ways to speed up the initial checkout -- which is the only place `fetch` is used. I tried your earlier suggestion but `gclient` threw some error about not being properly configured. However, running `fetch --nohooks --no-history android` speed things up quite a bit. I'm also thinking of changing the `gclient sync` command to `gclient sync --no-history --shallow --force -reset`.

It be greatly appreciated if you could link me to any resources with info on how to bootstrap Android builds without `depot_tools`. I need to look over the `ungoogled-chromium-android` builds and see what they ended up doing

**Comment by uazo** [comment]
> but gclient threw some error about not being properly configured.

sorry you are right, that is if you have already initialized the directory, try this

```
gclient config https://chromium.googlesource.com/chromium/src.git
echo "target_os=['android']" >>.gclient

VERSION=$( cat ~/bromite/build/RELEASE )
git clone --depth 2 https://chromium.googlesource.com/chromium/src.git +refs/tags/$VERSION:chromium_$VERSION
gclient sync --no-history -D

git remote remove origin
```
I think it should still work, it's been a while since I cleaned the home.
excellent the `no-history` suggestion, thanks.

> It be greatly appreciated if you could link me to any resources with info on how to bootstrap Android without depot_tools.

sorry, I have nothing about it.


instead if you have suggestions on how to speed up the build (without upgrading the ram :) I'm all ears!
I've seen this but haven't tried it yet https://chromium.googlesource.com/infra/goma/server

**Comment by nikolowry** [comment]
@uazo I'll be creating new feature branches for bromite-builder for:
- Checkout optimizations
- Using a local bromite repo instead of the release tar

I'll @ you in those pull requests when they're ready for review. Hopefully I'll be able to find some time this week for both of those

**Comment by csagan5** [comment]
@uazo did you use the mtool I shared? that speeds up builds massively already. I use it in conjunction with ccache.

**Comment by uazo** [comment]
> did you use the mtool I shared? 

yes, very useful. thanks it works great.

**Pull request merged**
