### PR TITLE
fix proxy and bookmark page

### LINKED ISSUE #891: Bookmarks don't work on 88.0.4324.95
### Bromite version
Version: `88.0.4324.95`
Arch: `arm`
Android version: `9.0`
Device model: `nx569j`

### Is this bug about the SystemWebView?
No.

### Is the bug reproducible with latest version?
Yes
.
### Can the bug be reproduced with corresponding Chromium version?
I don't know.

### Is the bug a crash?
No,

### Describe the bug
Bookmarks don't work on 88.0.4324.95.

### Steps to reproduce the bug
1. Open any bookmark.
2. Nothing happens - it just redirects to empty Mobile Bookmarks.

### Expected behavior
When you click on a bookmark, it opens a site in bookmark.

### PR DESCRIPTION
**Pull request by uazo**
fixes https://github.com/bromite/bromite/issues/891 https://github.com/bromite/bromite/issues/890

I deleted the useless `Revert-Remove-ChromeActivity-reference-from-BookmarkPage.patch`.
Tell me if it's okay

### CODE REVIEW

**Comment by csagan5** [comment]
For the proxy I had already applied a similar fix; for the bookmarks, glad you could find a simpler way, will use your patch.

**Review by csagan5 — APPROVED** [review]

**Comment by uazo** [comment]
perfect, if you want I can also fix the problem of the wrong thread and missing write permissions (dcheck failed, always present and visible only in debug). Maybe I also put the config of the destination folder in it...

**Comment by csagan5** [comment]
Sure, but please wait for the new patches to be released.

**Comment by csagan5** [comment]
@uazo I have pushed the patches, the release will come later as builds finish; you can already use them, if there are no build issues they will not change.

**Pull request merged**
