### PR TITLE
Update zh_CN translations

### PR DESCRIPTION
**Pull request by zhmars**
Changes:
- Add translations for Bromite #1865
- Update translations for `History-number-of-days-privacy-setting.patch`

### CODE REVIEW

**Comment by csagan5** [comment]
Thanks!

**Comment by csagan5** [comment]
Unfortunately it is failing with this error:
```
ERROR: 'zh-CN' translation of message id 5118676864324397542 does not match                                                                                                                                                                                                                                                   
Exception during parsing of translations/android_chrome_strings_zh-CN.xtb 
```

So I have removed that entry.

**Comment by zhmars** [comment]
This is the case I mentioned in https://github.com/bromite/bromite/issues/1865#issuecomment-1066096071 . 

`5118676864324397542` is the message id of `<ph name="APP_NAME">%1$s<ex>Bromite</ex></ph> storage`. I assume that is the string after your search&replace. But it seems wrong here. Would you mind telling me the string after your change?

**Comment by csagan5** [comment]
This is the block:
```
       <!-- Storage Preference UI strings for clearing storage. -->
       <message name="IDS_STORAGE_MANAGEMENT_ACTIVITY_LABEL" desc="Title for Chrome's Manage Space Activity.">
         <ph name="APP_NAME">%1$s<ex>Bromite</ex></ph> storage
       </message>
```

**Pull request merged**
