### PR TITLE
Fix favicons search for fallback

### LINKED ISSUE #788: Favicons are occasionally swapped
### Bromite version

Version: `86.0.4240.112`
Arch: `arm64`
Android version: `9.0`
Device model: `Galaxy S20`

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Describe the bug

The favicons are occasionally swapped for websites.

Upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=915374

### PR DESCRIPTION
**Pull request by uazo**
Patch for upstream issue #788

### CODE REVIEW

**Review by csagan5 — APPROVED** [review]

**Comment by csagan5** [comment]
Nice work; if you have the patience you could try submitting the patch directly upstream.

Note: in future please always put the patch before the last one, `Automated-domain-substitution.patch`.

**Comment by uazo** [comment]
> if you have the patience you could try submitting the patch directly upstream.

by now you have understood that I have little to do with English ...
if you want (and you have time) can you do it? there would also be the other proxy bug ...

> Note: in future please always put the patch before the last one

ah ah, certainly, no problem, I remembered you told me to put it down!

**Comment by csagan5** [comment]
> ah ah, certainly, no problem, I remembered you told me to put it down!

If I did, my mistake; it is better before `Automated-domain-substitution.patch` to avoid conflicts related to replacements

**Comment by csagan5** [comment]
> if you want (and you have time) can you do it? there would also be the other proxy bug ...

You should get credit for it; do not worry about English, when you open them I can quickly review them for you.

**Comment by uazo** [comment]
> You should get credit for it

thanks, but i don't care, if you want, do it in the name of the "bromite team"

**Pull request merged**
