### PR TITLE
Enable proxy config for the system network context

### PR DESCRIPTION
**Pull request by uazo**
The current patch comes from the implementation for ChromeOS which gets the proxy information from the local_state for the system network context.

This is not completely correct in Android, since the network context is never connected to any user profile and only gets the proxy information from the system.

With this change settings are moved from the Profile to LocalState, allowing the transparent use of the proxy also for SimpleURLLoaders (for example used for downloading Adblock filters and for favicons, which currently do not use any proxy even if set). Existing settings are automatically migrated on first startup.

### CODE REVIEW

**Comment by csagan5** [comment]
Great job in spotting this problem; I assume it is tested to work also when using the default system settings.

**Review by csagan5 — APPROVED** [review]

**Comment by csagan5** [comment]
@uazo even with this improvement DoH will not use the proxy, right?

**Comment by uazo** [comment]
well, but in theory, isn't it the proxy that resolves the address?

**Comment by csagan5** [comment]
The proxy uses DNS resolution to resolve the proxy address, then maybe after that it could use it. It seems complicated but in practice I verify that the DoH requests are not going through the proxy.

**Comment by uazo** [comment]
> The proxy uses DNS resolution to resolve the proxy address

do you mean chromium?

but I think it is correct because otherwise it would be a counter circuit.
just tried, if you try with a non-existent domain, the proxy responds with "lookup failed".

**Comment by csagan5** [comment]
> > The proxy uses DNS resolution to resolve the proxy address
> 
> do you mean chromium?

Also Bromite.

Yes, it is correct. I have documented the limitation here: https://github.com/bromite/bromite/wiki/DNS-over-HTTPS#limitations

**Pull request merged**
