### PR TITLE
[Build] [Patches] [Disable Safe Browsing] Hotfix for failing patch

### PR DESCRIPTION
**Pull request by nikolowry**
Applying `Disable-safe-browsing.patch` was failing due to `chrome/android/java/src/org/chromium/chrome/browser/preferences/privacy/PrivacyPreferences.java:36` and `chrome/android/java/strings/android_chrome_strings.grd:421`.

NOTE: When `Disable-safe-browsing.patch` fails, these additional patches fail as well(dependent patches):
- `Add-custom-tab-intents-privacy-option.patch`
- `Add-option-to-not-persist-tabs-across-sessions.patch`
- `Add-a-proxy-configuration-page.patch`

### CODE REVIEW

**Comment by csagan5** [comment]
@nikolowry thanks for the PR, I wonder why the patch failed though - perhaps needs to be applied with some fuzz factor?

I had already updated the patches because of #387 and #388 but I had not yet released them because I was planning to do that on next release.

I will now push the fixed patches that I already have; please see if there is anything from this PR that could still be submitted?

**Comment by nikolowry** [comment]
#387 is able to be replicated with the patch in this pull request (I never enable it, so it would have gone unnoticed by me) and #388 never effected me (but I only built up to 77.0.3865.95 during the last major releases).

I can build with your patch fixes today and report back on #387

**Comment by csagan5** [comment]
> #387 is able to be replicated with the patch in this pull request

Alright, thanks, I will give a look for next build - it is perhaps another patch mishap.

> I wonder why the patch failed though

This mystery remains though.

**Comment by csagan5** [comment]
@nikolowry you mean that #387 (and not #388) is still present? In this case can you test if #375 is really solved?

**Comment by nikolowry** [comment]
#387 was present with the patch provided by me in this pull request -- just finished building with https://github.com/bromite/bromite/commit/28e950d9beaafe30f683959d1789cf9915ac8d38 and can confirm it is resolved with that commit

**Comment by nikolowry** [comment]
> I wonder why the patch failed though

I'm no diff/patch algorithm expert, but I'm assuming the changes in `PrivacyPreferences.java` wasn't able to be applied because of `Revert-Remove-pre-unified-consent-code-in-sync-and-privacy-directory.patch`. If it happens again, it might be worth the effort to try and consolidate those two patches.

**Pull request closed without merging**
