### PR TITLE
Patches for v108

### PR DESCRIPTION
**Pull request by csagan5**
## Description

Started porting the top patches, will follow up with more.

## All submissions

* [x] there are no other open [Pull Requests](../../../pulls) for the same update/change
* [x] Bromite can be built with these changes
* [ ] I have tested that the new change works as intended (AVD or physical device will do)

### Format

* [x] patch subject and filename match (e.g. `Subject: Alternative cache (NIK-based)` -> `Alternative-cache-NIK-based.patch`)
* [x] patch description contains explanation of changes
* [x] no unnecessary whitespace or unrelated changes

### CODE REVIEW

**Comment by uazo** [comment]
OK, let's see how to organise ourselves.

[here](https://github.com/uazo/bromite/tree/next-v108/build/patches) is my version (final, can be build, even the windows version), how do you propose to continue? do I pull you onto this branch with only the changes to my patches? do I put the others on there too?

**Comment by csagan5** [comment]
> final, can be build, even the windows version

If there are changes for building the Windows version in the PRs you submit please mention it explicitly because I am not accepting these for now.

> how do you propose to continue? do I pull you onto this branch with only the changes to my patches?

You can open a PR with the patches that you maintain and I will review it to merge it.

> do I put the others on there too?

For new patches it's better a separate PR, you can put all of them into 1 and we discuss there.

**Comment by uazo** [comment]
> If there are changes for building the Windows version in the PRs

everything is separate until you say ok

>> do I put the others on there too?
>
> For new patches

I actually meant the old ones adapted to 108

**Comment by uazo** [comment]
Any particular reason why kCriticalClientHint results as enabled? see https://github.com/bromite/bromite/blob/master/build/patches/Client-hints-overrides.patch#L72
EDIT: also kAcceptCHFrame

**Comment by uazo** [comment]
same for `kExperimentsForAgsa` https://github.com/bromite/bromite/blob/master/build/patches/Disable-AGSA-by-default.patch#L272

**Comment by uazo** [comment]
another strange thing
```
--- a/chrome/android/java/src/org/chromium/chrome/browser/privacy/settings/PrivacySettings.java
+++ b/chrome/android/java/src/org/chromium/chrome/browser/privacy/settings/PrivacySettings.java
@@ -58,8 +58,6 @@ public class PrivacySettings
     private static final String PREF_SECURE_DNS = "secure_dns";
     private static final String PREF_DO_NOT_TRACK = "do_not_track";
     private static final String PREF_CLEAR_BROWSING_DATA = "clear_browsing_data";
-    private static final String PREF_PRIVACY_SANDBOX = "privacy_sandbox";
-    private static final String PREF_PROXY_OPTIONS = "proxy";
     private static final String PREF_PRIVACY_GUIDE = "privacy_guide";
     private static final String PREF_INCOGNITO_LOCK = "incognito_lock";
```
https://github.com/bromite/bromite/blob/master/build/patches/Disable-FLoC-and-privacy-sandbox.patch#L44

why remove `PREF_PROXY_OPTIONS` ? And most importantly, how does it build?

**Comment by uazo** [comment]
I'm sorry to bother you but also `kKeepPrefetchedContentSuggestions` see https://github.com/bromite/bromite/blob/master/build/patches/Disable-NTP-remote-suggestions-by-default.patch#L46

**Comment by csagan5** [comment]
> I'm sorry to bother you

What would be the bother?

> Any particular reason why kCriticalClientHint results as enabled?
> also `kKeepPrefetchedContentSuggestions`
> same for `kExperimentsForAgsa`

There is also `AcceptCHFrame`, I will fix them before next release; this was not intentional, they are all search/replace mistakes.

**Comment by csagan5** [comment]
> why remove `PREF_PROXY_OPTIONS` ? And most importantly, how does it build?

I removed it accidentally; it builds because it is unused, so I will remove it from the proxy UI patch.

It was introduced here: https://github.com/bromite/bromite/blob/32049708d5898fc1af3da6e189f7a72265f916c6/build/patches/Add-a-proxy-configuration-page.patch#L71

But it has been unused for long time.

**Comment by uazo** [comment]
you should changes also all

`extern const base::Feature xxx`  --->  `BASE_DECLARE_FEATURE(xxx);`

the result is the same but the style has been changed.
if you want I'll make you a pull, I had to merge your version into mine anyway.

**Comment by csagan5** [comment]
Sure, if you have already done it please submit it. I only changed those which were breaking.

**Comment by uazo** [comment]
> if you have already done it please submit it.

no, I'm doing it, and it's really boring and complex.
for example:

MINE:
```
   base::Value Encode(
       const BookmarkNode* bookmark_bar_node,
       const BookmarkNode* other_folder_node,
       const BookmarkNode* mobile_folder_node,
+      const BookmarkNode* tabs_folder_node,
       const BookmarkNode::MetaInfoMap* model_meta_info_map,
       const BookmarkNode::MetaInfoMap* model_unsynced_meta_info_map,
```

YOUR:
```
   base::Value Encode(
       const BookmarkNode* bookmark_bar_node,
       const BookmarkNode* other_folder_node,
+      const BookmarkNode* tabs_folder_node,
       const BookmarkNode* mobile_folder_node,
       const BookmarkNode::MetaInfoMap* model_meta_info_map,
       const BookmarkNode::MetaInfoMap* model_unsynced_meta_info_map,
```
the difference is subtle, but there is a bug? I must, merge, apply and verify... lungooooo
I really need something to automatically check the differences...

**Comment by uazo** [comment]
also:

MINE:
```
 extern const char kReduceUserAgentPlatformOsCpuName[];
 extern const char kReduceUserAgentPlatformOsCpuDescription[];
 
+extern const char kSiteEngagementName[];
+extern const char kSiteEngagementDescription[];
+
 extern const char kSkipServiceWorkerFetchHandlerName[];
 extern const char kSkipServiceWorkerFetchHandlerDescription[];
```

YOURS:
```
 extern const char kSkipServiceWorkerFetchHandlerName[];
 extern const char kSkipServiceWorkerFetchHandlerDescription[];
 
+extern const char kSiteEngagementName[];
+extern const char kSiteEngagementDescription[];
+
 extern const char kWebSQLAccessName[];
 extern const char kWebSQLAccessDescription[];
```

absolutely the same, but for example, could we define an order to be followed? alphabetical for example?

**Comment by csagan5** [comment]
Then leave it, I will do it later, it's not an important change.

**Pull request merged**
