### PR TITLE
Add a flag to site engagement feature (default disabled)

### LINKED ISSUE #2022: Flag/setting to disable site engagement (affects which NTP tiles are displayed)
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

It used to be possible to hide all NTP tiles, although the site engagement was still calculated: https://github.com/bromite/bromite/discussions/1979#discussioncomment-2562394

### Describe the solution you would like

Disable site engagement so that only bookmarked sites will appear as NTP tiles.

### Describe alternatives you have considered

Completely hide the NTP by using a home page as NTP (feature reintroduced in v96, #1586)

### PR DESCRIPTION
**Pull request by uazo**
Fix for #2022

### CODE REVIEW

**Comment by csagan5** [comment]
This is not really disabling it, it is resetting it after each commit.

**Comment by uazo** [comment]
> This is not really disabling it, it is resetting it after each commit.

what do you mean then by disable?
currently the score is never saved, so it is always empty and all the related code is skipped, so it's basically disabled

**Comment by csagan5** [comment]
> currently the score is never saved

Currently the score is saved, this PR wants to reset it on every commit.

Is this `score_dict_.reset();` necessary? That is what I mean. There is no other way for the user to reset it (other than reinstalling)?

**Comment by uazo** [comment]
> Is this score_dict_.reset(); necessary?

yes, to respect the `std::move(score_dict_)` otherwise skipped

> There is no other way for the user to reset it (other than reinstalling)?

do you intend the current score? by deleting the site settings from "Clear browsing data"

**Comment by uazo** [comment]
> this PR wants to reset it on every commit.

I did not understand then.
This PR disables the feature, but does not delete the current scores.
deleting the current score would be like deleting the data in startup, and at that point why not delete the cookies, as well as the point (in the code) is the same?

**Pull request merged**
