### PR TITLE
add item in main_menu_regroup.xml resource

### LINKED ISSUE #771: Crash opening Android New Overflow Menu
**Bromite version**
Version: 86.0.4240.73 arm64 Android version: 9.0 Device model: SM-G950F (Samsung Galaxy S8)

**Is this bug about the SystemWebView?**
No

**Is the bug reproducible with latest version?**
Yes

**Can the bug be reproduced with corresponding Chromium version?**
No

**Is the bug a crash?**
Yes

**Describe the bug**
After enabling the flags `#tabbed-app-overflow-menu-icons` and `#tabbed-app-overflow-menu-regroup`, the app crashes when trying to open the menu. The solution is uninstall Bromite e then install it again or disable these flags should work too.

**Steps to reproduce the bug:**

1. Open the Chrome Flags (chrome://flags) and enable the flags `#tabbed-app-overflow-menu-icons` and `#tabbed-app-overflow-menu-regroup`
2. Restart the browser
3. Close the browser - close from the background too
4. Open the browser
5. Try to open the menu
6. See error (app crashes)

**Expected behavior**
After enabling those flags, the app should open the menu normally.

**Screenshots**

Flags
chrome

New Overflow Menu
chrome_new_menu

### PR DESCRIPTION
**Pull request by uazo**
fixes #771 

we have to choose a suitable icon especially for exit_id

### CODE REVIEW

**Comment by frankjrp** [comment]
> we have to choose a suitable icon especially for exit_id

What about these two icons?

**View source**
https://icons8.com/icon/89500/source-code

**Exit**
https://icons8.com/icon/Q1xkcFuVON39/exit

**Colors in both icons**
Background: #FFFFFF
Recolor: #A6A6A6

**Example**
icons

**Review by csagan5 — APPROVED** [review]

**Comment by uazo** [comment]
@frankjrp never added new icons, but i think chromium needs svg path, look at https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/res/drawable/ic_cloud_offline_24dp.xml

**Comment by frankjrp** [comment]
@uazo I tried to find out how the icons are linked to the menu, but I didn't understand how it works, it seems that some icons are svg and others can be a png file.

**I was looking at the android menu xml:**
https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/res/menu/main_menu.xml

**And the new menu regroup:**
https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/res/menu/main_menu_regroup.xml

For example: the new incognito tab icon can be found here as a PNG file:
https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/res/drawable-hdpi/incognito_simple.png;l=1?q=incognito_simple&ss=chromium

However, I am not sure if I am analyzing the correct files and paths.

It would be nice if you could do some tests with a png file to see whether it will work or not.

incognito

folders

**Comment by uazo** [comment]
yes, it works!

image

I use this https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/res/drawable-hdpi/ic_exit_to_app_white_24dp.png

**Pull request merged**
