### PR TITLE
Enable update notification

### PR DESCRIPTION
**Pull request by uazo**
in the end I took the patch of @wchen342 and modified it, it came easier for me.
the logic is this:

- two new properties `BUILD_TIME` and `BUILD_TARGET_CPU` are inserted in the java class `org.chromium.build.BuildConfig`, the first taken from the same source as `GetBuildTime()`, the second taken directly from the args
- if enabled by the user (default is disabled), every 7 days (configurable in the code), a `HEAD` request is made to the page built in `BromiteInlineUpdateController.java`, actually `UPDATE_VERSION_URL + "bromite_" + BuildConfig.BUILD_TARGET_CPU + ".apk"`
- if the `Last-Modified` is greater than `BUILD_TIME`, the notification appears: that leads to `getDownloadUrl()` in an incognito page

The request is made by the native to have support for the proxy (the java side is always direct) and is without cookies.

Currently nothing is downloaded automatically, it is always the user who will have to download and install. To make it easier to find the correct file I have added `arch` to download page
`
"https://github.com/bromite/bromite/releases/latest?arch=" + BuildConfig.BUILD_TARGET_CPU;
`
but we can find an alternative.

Fix for #706

### CODE REVIEW

**Comment by csagan5** [comment]
As for the update URL, I found that it is possible to link directly to GitHub:
```
https://github.com/bromite/bromite/releases/latest/download/arm64_ChromePublic.apk
https://github.com/bromite/bromite/releases/latest/download/arm_ChromePublic.apk
https://github.com/bromite/bromite/releases/latest/download/x86_ChromePublic.apk
https://github.com/bromite/bromite/releases/latest/download/arm64_ChromePublic.apk
```

Can you please adjust the URL to use this pattern instead?

**Comment by uazo** [comment]
one more thing, by chance you have the files available
```
build/util/LASTCHANGE
build/util/LASTCHANGE.committime

source: build/compute_build_timestamp.py
```
of the current build? can you keep the next ones for verification?
I'm curious to see if they are the same regardless of effective compile time.

can you also verify that the `Last-Modified` matches that value? because I guess you need to do a `touch` of the apk file

**Comment by csagan5** [comment]
> one more thing, by chance you have the files available
> 
> ```
> build/util/LASTCHANGE
> build/util/LASTCHANGE.committime
> 
> source: build/compute_build_timestamp.py
> ```
> 
> of the current build? can you keep the next ones for verification? I'm curious to see if they are the same regardless of effective compile time.

They look like this:
```
10 Oct  7 23:54 build/util/LASTCHANGE
10 Oct  7 23:46 build/util/LASTCHANGE.committime
```
And the latter contains `1633568863`; `build/compute_build_timestamp.py` explains how these work.

> can you also verify that the `Last-Modified` matches that value? because I guess you need to do a `touch` of the apk file

The APK will always have a timestamp larger than the build timestamp because it is generated after the build, so I do not think we need to worry about this.

**Comment by csagan5** [comment]
Can you please resolve the conflict? I am going to try this on v94.

**Comment by uazo** [comment]
> We do not need anything related to build time and `Last-Modified`: the version check alone will suffice. 

OK, i will drop unused code

> Also: did you solve the problem about how to get the version from the first `location:` header?

yes, it works

**Comment by csagan5** [comment]
There is a still conflict and the branch is protected so I cannot solve it myself...

**Comment by csagan5** [comment]
It's not a big problem, I can always cherry-pick the commits - but then on GitHub it will not show as "merged" but rather "closed".

> do you know which option I need to activate to allow you the changes?

Probably adding me as collaborator would work?

> or maybe it is better that I create the branches directly in the Bromite repo?

Up to you, it is not a big deal.

**Comment by uazo** [comment]
> Probably adding me as collaborator would work?

Done!

**Comment by csagan5** [comment]
> > Probably adding me as collaborator would work?
> 
> Done!

I cannot accept that as it shares too much information for the invite.

I just noticed that it performs two HEAD checks, there must be somewhere a bug that makes it perform the operation twice; will try to figure this out.

**Comment by csagan5** [comment]
> I did that to follow the redirect to the end anyway.

What would it need it for?

**Comment by uazo** [comment]
> What would it need it for?

I left it if in the future (you or me) wanted to retrieve more from the actual `HEAD` of the file, I didn't remove it because I noticed that you don't like the commented codes.
The real `HEAD` is taken in `EndpointFetcher::OnURLLoadComplete`: consider that code must remain as it runs there in case there is no internet connection

**Comment by csagan5** [comment]
It seems to be always empty; you can see how I adjusted the code as soon as I publish the patches for v94.

**Comment by uazo** [comment]
> you can see how I adjusted the code as soon as I publish the patches for v94.

yes, how you did is fine

> Is that response_->redirect_url always empty or always non-empty?
> It seems to be always empty

in the hypothesis of having more redirects before reaching the url of the file, the first time is empty, the following ones are not.


```
1.  if (response_->redirect_url.empty()) {
2.    response_->redirect_url = url_.spec();
3.    response_->response = std::to_string(redirect_info.status_code);
4.  } else {
5.    LOG(INFO) << "BromiteUpdater: redirect URL is not empty, status code is " << redirect_info.status_code;
6.  }
7.  std::move(endpoint_fetcher_callback_).Run(std::move(response_));
```

so, having changed (7), the else to (5) will never be reached

**Pull request merged**
