### PR TITLE
Import patches to make WebView work on Tiramisu

### PR DESCRIPTION
**Pull request by chirayudesai**
This is for M105

* Patches are from M106
* Needed to make WebView work on Android 13
* Still works on Android 12 as well.

Change-Id: I275f7a6f28c0dd0fb9ef8eb3aafe2d796a9d5da7

## Description

*Please explain here what feature or bugfix these changes are addressing and why they should be included*

## All submissions

* [x] there are no other open [Pull Requests](../../../pulls) for the same update/change
* [ ] Bromite can be built with these changes
* [x] I have tested that the new change works as intended (AVD or physical device will do)

### Format

* [x] patch subject and filename match (e.g. `Subject: Alternative cache (NIK-based)` -> `Alternative-cache-NIK-based.patch`)
* [x] patch description contains explanation of changes
* [x] no unnecessary whitespace or unrelated changes

### CODE REVIEW

**Comment by chirayudesai** [comment]
@uazo I see you have a port for M105 so I only put this up, it should apply cleanly on top of that.

M104 needs some more patches for this to cleanly apply but I don't know if there's going to be another release of that here so I didn't bother with that. Let me know if that's needed however.

**Comment by uazo** [comment]
> I see you have a port for M105 so I only put this up, it should apply cleanly on top of that.

yes, it is to verify that my patches are not giving to csagan5 troubles on rebase.

regarding the webview, unfortunately I cannot compile it because it is not supported by my build environment

**Comment by csagan5** [comment]
> it is to verify that my patches are not giving to csagan5 troubles on rebase.

It actually was easy this time, didn't have any major issue.

**Comment by csagan5** [comment]
> I don't know if there's going to be another release of that here so I didn't bother with that. Let me know if that's needed however.

No need.

Do any of these patches change the minimum required SDK version?

**Comment by chirayudesai** [comment]
> > I don't know if there's going to be another release of that here so I didn't bother with that. Let me know if that's needed however.
> 
> No need.
> 
> Do any of these patches change the minimum required SDK version?

No, mindSdk stays at 29 like before. targetSdk jumps to 33 from 31

It can also be seen in the `Update-to-Android-T-SDK.patch` patching which updates the expected manifest.

**Comment by csagan5** [comment]
> Bromite can be built with these changes

@chirayudesai build fails with these patches?

**Comment by chirayudesai** [comment]
> > Bromite can be built with these changes
> 
> @chirayudesai build fails with these patches?

Untested, I was waiting for the Bromite M105 changes. 

Just rebased this, trying it now.

It works fine in general with M105

**Comment by csagan5** [comment]
I tried to build this but I get:
```
ninja: error: '../../third_party/android_sdk/public/platforms/android-33/android.jar', needed by 'gen/base/android_runtime_jni_headers/Runnable_jni.h', missing and no known rule to make it
ninja: error: '../../third_party/android_sdk/public/platforms/android-33/android.jar', needed by 'gen/base/android_runtime_jni_headers/Runnable_jni.h', missing and no known rule to make it
```

@chirayudesai can you please re-open it? It closed automatically because of the branch merge.

**Comment by chirayudesai** [comment]
> I tried to build this but I get:

You'll have to run `gclient runhooks` with these patches applied so that it can download the latest jars.


> @chirayudesai can you please re-open it? It closed automatically because of the branch merge.


I didn't see a way to re-open this, so I rebased and opened https://github.com/bromite/bromite/pull/2349 instead

**Pull request closed without merging**
