### PR TITLE
Updated i18n zh_CN support for v83

### PR DESCRIPTION
**Pull request by zhmars**
Ref: https://github.com/bromite/bromite/issues/546

Hi, this is Simplified Chinese(zh-CN)'s patch for i18n support. It should be applied successfully on latest Bromite release. But I haven't build it since setup the build environment is harder than I thought.

Could you test or review this? Any help is much appreciated.

### CODE REVIEW

**Comment by csagan5** [comment]
I will try; @zhmars how did you create this?

**Comment by zhmars** [comment]
Many thanks for your time.

I readed the comment you posted in https://github.com/bromite/bromite/pull/302#issuecomment-492653023 and google it. It seems all I need is updating the `android_chrome_strings_zh-CN.xtb` file.

For strings to be translated, all were taken from bromite patches list except the `About Bromite` string. For translation ids, they were generated by `chromium/tools/grit`.

**Comment by csagan5** [comment]
Great!

See if https://fdroid.bromite.org/bromite/arm64_ChromeModernPublic_v83_i18n.apk works, I built it including your patch.

**Beware**: this is a more recent version of Bromite (v83) and due to be released soon, but you cannot go back to v81 stable without erasing the data in case there are other problems with it.

**Comment by zhmars** [comment]
Thanks, csagan5.

Most of them work except the `Secure DNS` menu, its translation should locate in `generated_resources_zh-CN.xtb`. There is also another `About Bromite` menu, which should be translated in `google_chrome_strings_zh-CN.xtb`

I have created a new patch for these. Could you try to rebuild the package?

**Comment by csagan5** [comment]
@zhmars it should work, see https://fdroid.bromite.org/bromite/arm64_ChromeModernPublic_v83_i18n_v2.apk

**Comment by zhmars** [comment]
Sorry for late reply. The DNS menu has been translated successfully, but `About Bromite` menu is not. I decide to create a new patch,

Included changes:

- minor fixes for ad blocking menu.
- add translation to `chromium_strings_zh-CN.xtb` instead of `google_chrome_strings_zh-CN.xtb`, which should fix `About Bromite` menu.

**Comment by csagan5** [comment]
This will have to wait for next release; you can solve the conflict meanwhile by overwriting the patch.

**Comment by zhmars** [comment]
Ok. The patch has resynced for v83.

**Comment by csagan5** [comment]
@zhmars I have added your latest patch on `master`, will post on the issue when it's possible to test it again.

**Comment by zhmars** [comment]
No worries. Just ping me when it ready and I'll test the latest.

**Pull request closed without merging**
