### PR TITLE
Added link to the issue on the F-Droid repository

### PR DESCRIPTION
**Pull request by anewuser**
People reading the FAQ to know why it isn't on app stores will be interested in following this issue.

### CODE REVIEW

**Comment by csagan5** [comment]
The issue to begin reading about this is #4, not that one, and what you mentioned is not the only reason why Chromium forks are not on F-Droid.

**Comment by anewuser** [comment]
@csagan5 Please correct the text then to prevent people from creating new issues about this.

**Comment by csagan5** [comment]
@anewuser before creating a new issue you are kindly requested to search the issue tracker; this is valid for any issue, not just about F-Droid.

**Comment by anewuser** [comment]
@csagan5  I had already found it but I was trying to save people's time, since the FAQ answer isn't clear, and several issues mentioning your custom F-Droid server come up when people look it up. Also, the most recent issue about this has  been closed without any comment (#592).

**Comment by csagan5** [comment]
@anewuser that issue is missing the issue template; the issue tracker cannot be used to ask questions, just for bug reports or feature requests.

The FAQ answer is clear in stating that Bromite is not on the F-Droid official repository, it does not need to justify it. That would be another question: "Why is Bromite not on the F-Droid official repository?" But that's not a question to put on FAQs, forums/discussion aggregators are better suited for that. It spawns a long, complex discussion, it has some technical aspects and we already did it on multiple issue trackers.

**Comment by csagan5** [comment]
I could add a link to issue #4, but the discussion has happened also on GitLab and other places, so it would not be comprehensive. I am not adding the link because it would be incomplete without adding the other links, and then after adding all the links that give a good context it would not look like a FAQ answer anymore.

**Comment by anewuser** [comment]
Thank you for the in-depth response. I personally was just looking for an issue I could subscribe to and be notified about when/if the browser is added to the main repository, but now I understand you're trying to avoid technical debates and misunderstandings.

**Comment by csagan5** [comment]
I am also looking for that: an issue about adding Chromium to F-Droid. Once that happens Bromite can be easily added as well.

**Pull request closed without merging**
