### PR TITLE
Add patch for always-incognito crashes fixes

### LINKED ISSUE #135: Crash when trying to open an intent as normal page with incognito mode
**Bromite version**

Version: `69.0.3497.91`
Arch: `arm64`
Android version: `nougat`

**Is the bug reproducible with latest version?**
Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No.

**Is the bug a crash?**
Yes.

**To Reproduce**
1. Enable always-incognito mode
2. Allow custom tab intents (default)
3. Open an intent URL from an app
4. Click on the 3-dots menu -> Open in Bromite

Related to #18

### LINKED ISSUE #453: Always incognito mode crash when Bromite is not running
Version: v79.0.3945.94 and v79.0.3945.100
Arch: arm64
Android version: 8.0
Device model: p10 lite

Is this bug about the SystemWebView?

No

Is the bug reproducible with latest version?

Yes

Can the bug be reproduced with corresponding Chromium version?

No

Is the bug a crash?

Yes

Describe the bug

When 'open links in incognito tabs always' is enabled, opening links from external apps example youtube, gmail, makes bromite to crash on launch. This doesn't happen if bromite is already running in the background, the link successfully opens in a new tab.
Latest working version is v78.0.3904.130.
Link to pastebin logcat https://defuse.ca/b/1OTHi8dc

Issue https://github.com/bromite/bromite/issues/450 might be related.

Steps to reproduce the bug

Enable always open incognito mode and try open link with random apps

### PR DESCRIPTION
**Pull request by csagan5**
Fixes #453 and fixes #135

### CODE REVIEW

**Comment by uazo** [comment]
I propose another solution that I like best, there is no change in the intent handler, nor any uncomment.

I tried to make the diff autonomously without success, if you write me the command you use I can commit to this branch.

anyway:

```
--- chrome/android/java/src/org.original/chromium/chrome/browser/init/StartupTabPreloader.java  2020-04-15 09:38:56.164868500 +0200
+++ chrome/android/java/src/org/chromium/chrome/browser/init/StartupTabPreloader.java   2020-04-20 12:39:09.157934911 +0200
@@ -37,4 +37,7 @@
 import org.chromium.url.GURL;

+import org.chromium.base.ContextUtils;
+import org.chromium.chrome.browser.AlwaysIncognitoLinkInterceptor;
+
 /**
  * This class attempts to preload the tab if the url is known from the intent when the profile
@@ -175,7 +178,13 @@
         GURL url = UrlFormatter.fixupUrl(getUrlFromIntent(intent));

+        // CM: always incognito
+        boolean isincognito = false;
+        if (ContextUtils.getAppSharedPreferences().getBoolean(AlwaysIncognitoLinkInterceptor.PREF_ALWAYS_INCOGNITO, false)) {
+          isincognito = true;
+        }
+
         ChromeTabCreator chromeTabCreator =
-                (ChromeTabCreator) mTabCreatorManager.getTabCreator(false);
-        WebContents webContents = WebContentsFactory.createWebContents(false, false);
+                (ChromeTabCreator) mTabCreatorManager.getTabCreator(isincognito);
+        WebContents webContents = WebContentsFactory.createWebContents(isincognito, false);

         mLoadUrlParams = new LoadUrlParams(url.getValidSpecOrEmpty());
@@ -191,5 +200,5 @@
         // later if the loadUrlParams etc... match.
         mTab = TabBuilder.createLiveTab(false)
-                       .setIncognito(false)
+                       .setIncognito(isincognito)
                        .setLaunchType(TabLaunchType.FROM_EXTERNAL_APP)
                        .setWindow(mWindowAndroid)
```

```
--- chrome/android/java/src/org.original/chromium/chrome/browser/tabmodel/TabPersistentStore.java       2020-04-15 09:38:56.240864900 +0200
+++ chrome/android/java/src/org/chromium/chrome/browser/tabmodel/TabPersistentStore.java        2020-04-20 12:38:17.567039620 +0200
@@ -46,4 +46,6 @@
 import org.chromium.content_public.browser.UiThreadTaskTraits;

+import org.chromium.chrome.browser.AlwaysIncognitoLinkInterceptor;
+
 import java.io.BufferedInputStream;
 import java.io.ByteArrayInputStream;
@@ -595,4 +597,11 @@
         }

+        if (ContextUtils.getAppSharedPreferences().getBoolean(AlwaysIncognitoLinkInterceptor.PREF_ALWAYS_INCOGNITO, false)) {
+          if( isIncognito == false ) {
+            Log.w(TAG, "Failed to restore tab: it's not in incognito mode.");
+            return;
+          }
+        }
+
         TabModel model = mTabModelSelector.getModel(isIncognito);
         SparseIntArray restoredTabs = isIncognito ? mIncognitoTabsRestored : mNormalTabsRestored;
```

**Comment by csagan5** [comment]
> if you write me the command you use I can commit to this branch.

You would have to make a PR from this branch, it's not about the command.

> I propose another solution that I like best

This is more similar to what I was working on, but it did not work out very well. I can make a build for this version with your patch if you can test for both crashes.

**Comment by csagan5** [comment]
I have built it here: https://fdroid.bromite.org/bromite/arm64_ChromeModernPublic_patched_v3.apk

Does it fix #453 and #135?

**Comment by randomshell** [comment]
Fixes #453 for me.

Thanks @uazo @csagan5

**Comment by randomshell** [comment]
> Fixes #453 and #135

You need to repeat `fixes` before every issue or Github links only the first. [Documentation](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#closing-multiple-issues)

**Comment by uazo** [comment]
for #135 i tried with

1. ``
adb shell am start -a android.intent.action.VIEW -d http://www.stackoverflow.com --es android.support.customtabs.extra.SESSION "1"
``

2. open in chrome
3. Click on the 3-dots menu -> Open in Bromite

it works

**Comment by uazo** [comment]
but if you click on the "privacy policy" bottom link  it crash with

``chromium:` [FATAL:tab_android.cc(243)] Check failed: GetProfile()->IsOffTheRecord() == incognito (0 vs. )``

I think it's the same reason as #132 since that tab is not in incognito mode

**Comment by uazo** [comment]
here https://bugs.chromium.org/p/chromium/issues/detail?id=1023759 some info

**Comment by csagan5** [comment]
> You need to repeat `fixes` before every issue or Github links only the first.

Was not aiming to get it automatically closed by GitHub, but sure.

> here https://bugs.chromium.org/p/chromium/issues/detail?id=1023759 some info

@uazo support for incognito CCTs is not in v81?

We can merge the fix of this PR and work separately on the remaining issues?

**Comment by uazo** [comment]
> We can merge the fix of this PR and work separately on the remaining issues?

for me certainly

**Comment by csagan5** [comment]
> chromium: [FATAL:tab_android.cc(243)] Check failed: GetProfile()->IsOffTheRecord() == incognito (0 vs. )

There is something missing here? It should say `0 vs 1`?

Any idea why the profile is not the incognito one there?

**Comment by uazo** [comment]
> There is something missing here? It should say 0 vs 1?

Code seems have tree values: 0, 1 e null

> Any idea why the profile is not the incognito one there?

from what - I begin - to understand, anonymous browsing is initialized by the ChromeTabCreator

https://chromium.googlesource.com/chromium/src/+/master/chrome/android/java/src/org/chromium/chrome/browser/ChromeTabbedActivity.java#1676

and assigned

https://chromium.googlesource.com/chromium/src/+/master/chrome/android/java/src/org/chromium/chrome/browser/ChromeActivity.java#596

the patch (in https://github.com/bromite/bromite/blob/master/build/patches/Add-an-always-incognito-mode.patch#L141) always returns the incognito mode even if not requested (so getTabCreator (true) == getTabCreator (false)) this leads to a C ++ crash when the profile is checked, which is fine.
Therefore, it is mandatory that customtab are also anonymous.

The patch, however, seems simple: I try to make a pull request for #132

**Comment by csagan5** [comment]
Great, thanks for your contribution!

**Pull request merged**
