### PR TITLE
update timezone override patch for v86

### PR DESCRIPTION
**Pull request by uazo**
patch for v86.

### CODE REVIEW

**Comment by csagan5** [comment]
Thanks!

**Comment by csagan5** [comment]
@uazo I will commit the updated patches for v87 soon so that you can update this patch as well; my patches might not compile without errors but at least will allow you to update the patch meanwhile.

**Comment by csagan5** [comment]
@uazo done

**Comment by uazo** [comment]
great work!
I'll start tomorrow.

I was trying too but I'm stuck on `Disable-safe-browsing.patch`! but I swear that I will make it!
A silly question: but why not just leave it active with the offline database?
Another thing about version: last v87 version I found is 87.0.4280.62, you have used .57, I can ask you why?

**Comment by csagan5** [comment]
> I was trying too but I'm stuck on `Disable-safe-browsing.patch`! but I swear that I will make it!

It's double work; there is already the folks at ungoogled-chromium and Vanadium doing similar patch updates work. You can use already the patches I updated, right?

> A silly question: but why not just leave it active with the offline database?

You are probably referring to this: https://github.com/GrapheneOS/Vanadium/issues/35
I am not sure if "offline" really means offline in all cases; safe browsing used to be possible to disable completely during build.

> Another thing about version: last v87 version I found is 87.0.4280.62, you have used .57, I can ask you why?

Because when I started updating the patches it was .57

**Comment by uazo** [comment]
> It's double work; there is already the folks at ungoogled-chromium and Vanadium doing similar patch updates work. You can use already the patches I updated, right?

yes, yes, of course, I just want to try while I was waiting for you..
I have seen that some patch are easily applied with wiggle, others (mine!) require more work, I would like to understand how to optimize them for less maintenance

> I am not sure if "offline" really means offline in all cases;

from what I've seen it would seem so. would have to be investigated

> safe browsing used to be possible to disable completely during build

so, why that patch?

> Because when I started updating the patches it was .57

Ah, ok, sure!

another question (sorry if I disturb you), about the patch order, how do you decide it?

**Comment by csagan5** [comment]
> I would like to understand how to optimize them for less maintenance

There are some tricks, but in some cases nothing can be done.





> so, why that patch?

*Used*, it is not possible anymore to disable it. Without the patch it cannot be disabled.

> about the patch order, how do you decide it?

They are always by date of creation, unless they touch similar files; in those cases it is better to cluster them together.

**Comment by csagan5** [comment]
@uazo there is currently a problem with the patch for autoplay:
```
gen/components/browser_ui/site_settings/android/site_settings_jni_headers/WebsitePreferenceBridge_jni.h:178:13: error: function 'JNI_WebsitePreferenceBridge_GetAutoplayOrigins' has internal linkage but is not defined [-Werror,-Wundefined-internal]
static void JNI_WebsitePreferenceBridge_GetAutoplayOrigins(JNIEnv* env, const
            ^
gen/components/browser_ui/site_settings/android/site_settings_jni_headers/WebsitePreferenceBridge_jni.h:187:10: note: used here
  return JNI_WebsitePreferenceBridge_GetAutoplayOrigins(env,
         ^
```

I have updated the patches again; I can leave this issue to you. Let me know if you find a fix.

**Comment by uazo** [comment]
What's about this?

```
./../components/safe_browsing/core/file_type_policies.cc:53:40: error: use of undeclared identifier 'IDR_DOWNLOAD_FILE_TYPES_PB'
  return bundle.LoadDataResourceString(IDR_DOWNLOAD_FILE_TYPES_PB);
```

do you have same bug with yours?
Do I give up or do you want me to fix this too?

**Comment by uazo** [comment]
>> there is currently a problem with the patch for autoplay

> has internal linkage but is not defined

I'll take care of it, usually that error is due to the wrong number of arguments between `@native` in java and the counterpart c++

**Comment by csagan5** [comment]
> do you have same bug with yours?

No, but it could be because I did not start from scratch with the build.

**Comment by csagan5** [comment]
The `IDR_DOWNLOAD_FILE_TYPES_PB` is reproducible also for me when skipping the autoplay patch, which is currently broken.

I will try to fix this one about `IDR_DOWNLOAD_FILE_TYPES_PB`; if you can fix the autoplay and the timezone patch we can include them in the release for v87.

**Comment by uazo** [comment]
I have already fixed several compilation problems, I still don't know if chromium works. now I am waiting for the compilation to finish, later I will send them to you and then I do a pr with the fixup! (if you need it and if you want to compare it)

> if you can fix the autoplay and the timezone patch we can include them in the release for v87.

yes, as soon as i can compile

**Comment by csagan5** [comment]
Did you already fix the `IDR_DOWNLOAD_FILE_TYPES_PB` problem?

**Comment by uazo** [comment]
for now I've changed with

```
std::string FileTypePolicies::ReadResourceBundle() {
  //ui::ResourceBundle& bundle = ui::ResourceBundle::GetSharedInstance();
  return nullptr; // bundle.LoadDataResourceString(IDR_DOWNLOAD_FILE_TYPES_PB);
}
```

then I'll find if it's ok.
that file is the compiled version of `components/safe_browsing/core/resources/download_file_types.asciipb`, I think it's only for safe_browsing

**Comment by uazo** [comment]
look there is a rather difficult bug to find caused by `chrome/android/java/res/values/values.xml` (at least, it took me a while).

if you don't delete the strings

```
allow_custom_tab_intents_title
allow_custom_tab_intents_summary
close_tabs_on_exit_title
close_tabs_on_exit_summary
```

can't compile with indecipherable error (for me)

**Comment by csagan5** [comment]
> then I'll find if it's ok.

I was also thinking to remove those methods; I will try to compile with them removed.

> look there is a rather difficult bug to find caused by `chrome/android/java/res/values/values.xml`

What is the solution? They need to be moved elsewhere?

**Comment by uazo** [comment]
> What is the solution? They need to be moved elsewhere?

in my opinion they are not really needed, maybe they are the typo of some old version. at least when I had added the strings in the patches it was enough for me to insert in the `.grd`.
if It run I can confirm it.

**Comment by csagan5** [comment]
Yes, they should be in the `.grd`; please remove them from `values.xml`.

**Comment by uazo** [comment]
another cryptic error

```
FAILED: libchrome__combined.so libchrome__combined.so.TOC lib.unstripped/libchrome__combined.so
python "../../build/toolchain/gcc_solink_wrapper.py" --readelf="../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-readelf" --nm="../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm" --strip=../../buildtools/third_party/eu-strip/bin/eu-strip  --sofile="./lib.unstripped/libchrome__combined.so" --tocfile="./libchrome__combined.so.TOC" --output="./libchrome__combined.so" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-soname="libchrome__combined.so" -Wl,--version-script=gen/chrome/android/libchrome_linker_script.txt -Wl,--hash-style=gnu -Wl,-soname,libchrome.so --link-only -Wl,--fatal-warnings -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,-z,max-page-size=4096 -Wl,--color-diagnostics -Wl,--no-rosegment -Wl,--no-call-graph-profile-sort -Wl,--exclude-libs=libgcc.a -Wl,--exclude-libs=libvpx_assembly_arm.a --target=aarch64-linux-android21 -Wl,-mllvm,-enable-machine-outliner=never -Werror -Wl,--gc-sections -nostdlib++ --sysroot=../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -B../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64 -Wl,--warn-shared-textrel -Wl,--pack-dyn-relocs=android -Wl,-wrap,calloc -Wl,-wrap,free -Wl,-wrap,malloc -Wl,-wrap,memalign -Wl,-wrap,posix_memalign -Wl,-wrap,pvalloc -Wl,-wrap,realloc -Wl,-wrap,valloc -Wl,-wrap,strdup -Wl,-wrap,strndup -Wl,--dynamic-linker,/system/bin/linker64 -o "./lib.unstripped/libchrome__combined.so" @"./libchrome__combined.so.rsp"
ld.lld: error: undefined symbol: ProfileWriter::ProfileWriter(Profile*)
>>> referenced by bookmark_bridge.cc:714 (../../chrome/browser/android/bookmarks/bookmark_bridge.cc:714)
>>>               browser/bookmark_bridge.o:(BookmarkBridge::FileSelected(base::FilePath const&, int, void*)) in archive obj/chrome/browser/libbrowser.a

```

I try to solve. any suggestions?

**Comment by csagan5** [comment]
I would guess that `profile_writer.cc` is not in the corresponding `BUILD.gn`, or the constructor signature is invalid. I can fix this easily.

**Comment by uazo** [comment]
yes, I did that in `chrome/browser/BUILD.gn`

**Comment by uazo** [comment]
so, it's running! now I'll prepare the list of changes I made

**Comment by uazo** [comment]
https://gist.github.com/uazo/89608436196ac921a0ac25d0deff7d38

how do we divide the work?

**Comment by csagan5** [comment]
@uazo create a PR when you are done with the changes; I do not have other changes to submit and will wait for yours.

**Pull request merged**
