### PR TITLE
Updated patches for v79

### PR DESCRIPTION
**Pull request by csagan5**
Remaining issues:
* [x] crash when accessing Settings -> Privacy
* [ ] blank tabs when running on x86 emulators
* [x] addresses collection settings need to be unticked by default
* [x] NTP articles should be hidden

The upstream storage bug (https://bugs.chromium.org/p/chromium/issues/detail?id=1033655) is fixed in this version.

### CODE REVIEW

**Comment by csagan5** [comment]
@nikolowry I am opening a PR in case you or someone else wants to start experimenting with the patches for v79; there is still some work to be done before release.

**Comment by nikolowry** [comment]
@csagan5 thanks for the @! I won't be able to give anything a go until the weekend though

**Comment by csagan5** [comment]
@nikolowry no worries; I created the PR so that others can give a look when I am not.

The crash issue has been solved, will push the changes here ASAP; I am now looking at the blank rendering issue.

I am checking these flags:
* `enable-vulkan` (disabled by default)
* webcontent occlusion (doesn't apply to Android)
* `enable-service-worker-on-ui` (disabled by default)
* `enable-paint-holding`

**Comment by nikolowry** [comment]
@csagan5 this is off-topic, but it didn't really warrant an issue or mention -- so I'll just alert you to it some things I noticed previously in `GN_ARGS`:

- `symbol_level` is set twice on lines 30 and 31 
https://github.com/bromite/bromite/blob/bc3ef3746a01d21518908050132c4c9e7434b593/build/GN_ARGS#L30-31
- `exclude_unwind_tables` was dropped, see https://chromium.googlesource.com/chromium/src/+/e93c224ed2143f2cb29c11e15f8134d41563eaaf
- `remove_webcore_debug_symbols` was dropped, see https://chromium.googlesource.com/chromium/src/+/19ce23bd6302e6271b230a58fbb77dc5b539abdd

**Comment by csagan5** [comment]
@nikolowry I did not include the updated GN_ARGS here, but I had already fixed those - except for the duplicate, I will fix that too.

**Comment by csagan5** [comment]
Of all the flags I tried, nothing seems related to the blank tab issue.

I found another possibly related upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1032189

The adb log shows a tight loop of these when the issue is happening:
```
12-19 01:48:13.746 11277 11296 D EGL_emulation: eglMakeCurrent: 0xecadda00: ver 2 0 (tinfo 0xecae9710)
12-19 01:48:13.762  1767  1963 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 7479296
12-19 01:48:13.772 11277 11296 D EGL_emulation: eglMakeCurrent: 0xc9c46500: ver 2 0 (tinfo 0xecae9710)
12-19 01:48:13.788 11277 11296 E EGL_emulation: tid 11296: eglCreateSyncKHR(2094): error 0x3004 (EGL_BAD_ATTRIBUTE)
12-19 01:48:13.788 11277 11296 E chromium: [ERROR:gles2_cmd_decoder.cc(5997)] Error: 4 for Command kCreateGpuFenceINTERNAL
12-19 01:48:13.790 11277 11296 D EGL_emulation: eglCreateContext: 0xecace9a0: maj 2 min 0 rcv 2
12-19 01:48:13.791 11277 11296 D EGL_emulation: eglMakeCurrent: 0xecace9a0: ver 2 0 (tinfo 0xecae9710)
```

So it's possible upstream will fix it soon.

**Comment by csagan5** [comment]
Only the blank tab rendering on x86 issue is remaining now; I will merge it as I prepare a release.

Cc @wchen342

**Comment by wchen342** [comment]
Thanks for the patches! Dont know about the x86 bug but I will test on my build when I have time.

**Comment by csagan5** [comment]
@wchen342 keep an eye on `master` as I will release improved patches for next release

**Pull request merged**
