### PR TITLE
Minor changes to v98 patches

### PR DESCRIPTION
**Pull request by uazo**
no functionality changed.

small changes:
- elimination of excess blank lines
- moving the position of `g_browser_process->adblock_updater();` in `Bromite AdBlockUpdaterService` 
- fix overlap between `Disable privacy sandbox` and `JIT-less toggle`
- changed to `raw_ptr<BookmarkPermanentNode> tabs_collection_node_ = nullptr`
- removed last `$google_play_services_package` in `Remove binary blob integrations`

### CODE REVIEW

**Comment by csagan5** [comment]
> * changed to `raw_ptr<BookmarkPermanentNode> tabs_collection_node_ = nullptr`

Reason? It is not safe to use those if there is no logic to correctly free the objects from memory.

**Comment by csagan5** [comment]
> > It is not safe to use those if there is no logic to correctly free the objects from memory.
> 
> from what I understand instead the use of raw_ptr is [better](https://chromium.googlesource.com/chromium/src/+/ddc017f9569973a731a574be4199d8400616f5a5/base/memory/raw_ptr.md)

My bad, I thought none of those benefits were available for `raw_ptr`.

> we have no memory leak

We will still have memory leaks if the freed object contains pointers which are not `raw_ptr`, right?
Is this the case here?

**Comment by csagan5** [comment]
I will merge this but please let me know about the question above, memory leaks are serious issues.

**Comment by uazo** [comment]
> We will still have memory leaks if the freed object contains pointers which are not raw_ptr, right?
Is this the case here?

no, not necessarily. it depends on what is connected to that pointer, if it is a C++ object there is basically no problem, as long as the references are correctly moved. in case a class can be copied, the suitable measures are already foreseen in the chromium code.
`raw_ptr` resets the value of the pointer to NULL when the "c++ garbage collector" is correctly managed otherwise even the use of that is useless.

**Pull request merged**
