### PR TITLE
Reverse the order of appmenu

### LINKED ISSUE #2030: Move pop-up toolbar to the bottom when using bottom navigation-bar
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

No

### Is there a patch available for this feature somewhere?

probably yes, but I was not able to find it

### Describe the solution you would like

move the toolbar to the bottom when bottom navigation-bar is activated with the flag.

image

### Describe alternatives you have considered

N/A

### PR DESCRIPTION
**Pull request by uazo**
Fix for #2030

### CODE REVIEW

**Comment by uazo** [comment]
this is what appears:
image

**Comment by csagan5** [comment]
I think you might get users asking for the other order style.

**Comment by uazo** [comment]
> I think you might get users asking for the other order style.

ok, let's wait to see if there is demand

**Comment by csagan5** [comment]
I don't think you should add options for everything, it should stay the way it is.

**Comment by M86xKC** [comment]
Thanks!
Now I don't accidentally close bromite by accidentally double fat-fingering the menu icon.

**Pull request merged**
