### PR TITLE
WebGL & Device Model Fingerprinting Protection

### PR DESCRIPTION
**Pull request by uazo**
as you wrote https://github.com/bromite/bromite/issues/668, I propose a possible patch to hide vendor info in WebGLDebugRendererInfo.

tell me what you think and if you prefer a switch

### CODE REVIEW

**Comment by csagan5** [comment]
@uazo first we should discuss what changes to make; in #668 I did not intend that any patch submitted will be merged.

There is already a patch that adds a flag to disable WebGL.

**Comment by uazo** [comment]
I know it's okay if you don't merge!
let's talk about the patch.

> There is already a patch that adds a flag to disable WebGL.

why disable?

**Comment by csagan5** [comment]
> why disable?

If you do not disable it then one can still detect the device based on the available features/methods; there used to be [a patch like this one from ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium/blob/7ba01e6/patches/extra/ungoogled-chromium/disable-webgl-renderer-info.patch) in Bromite.

This change here you want to make would have the same problem.

**Comment by uazo** [comment]
> If you do not disable it then one can still detect the device based on the available features/methods

do you know something more?

> be a patch like this one from ungoogled-chromium in Bromite.

thanks, I will check next time

**Comment by csagan5** [comment]
> > If you do not disable it then one can still detect the device based on the available features/methods
> 
> do you know something more?

I would need to find the GitHub issues where this was discussed; obviously for Ungoogled-Chromium they think it's still worth disabling the text returned in these cases.

See also #131, for which I have a half-developed patch somewhere.

**Comment by csagan5** [comment]
See https://github.com/Eloston/ungoogled-chromium/issues/429#issuecomment-422129242
And the following comments.

This is a Bromite patch which was removing the returned information (before a flag to disable WebGL was added): https://github.com/bromite/bromite/blob/f21bb8a1d4a865d35db82389cec27b945b925cf3/patches/BRM052_Canvas-fingerprinting-mitigations-for-image-data-and-webGL.patch

**Comment by csagan5** [comment]
You can even submit this patch to ungoogled-chromium, it would help the complete the patch they still have.

**Comment by uazo** [comment]
ok, I get it, more complex than I thought.

**Pull request closed without merging**
