### PR TITLE
fix patch "Add exit menu item"

### LINKED ISSUE #673: Exit button not working from overview with no tabs open
### Bromite version

Version: `83.0...` 84.0.4147.119
Arch: `arm` or `arm64` or `x86` arm64
Android version: (example: `9.0`) 10
Device model: (example: `SM-G960UZKABST`) OP5T

### Is this bug about the SystemWebView?
Yes/No na

### Describe the bug

Exit button doesnt work IF there are no tabs open.

Screenshot_20200806-100348_1

### Steps to reproduce the bug

Steps to reproduce the bug:
1 open bromite
2 ensure there are no tabs open
3 menu->exit
### Expected behavior

bromite should exit but nothing happens.

### PR DESCRIPTION
**Pull request by uazo**
fixes https://github.com/bromite/bromite/issues/673

### CODE REVIEW

**Review by csagan5 — APPROVED** [review]
I had already added your fix; thanks.

**Comment by csagan5** [comment]
@uazo please see if the version in master is still OK? I had made it based on your first comment.

**Comment by uazo** [comment]
image

you can remove this.

**Comment by csagan5** [comment]
Makes sense, thanks.

**Pull request merged**
