### PR TITLE
Updated patches for v80

### PR DESCRIPTION
**Pull request by csagan5**
@nikolowry @wchen342 these are Bromite's patches for v80, I am however stuck at the following linking error.

I find it unusually cryptic and I am unable to understand what is the issue; I assume it's some problem with Java methods called from C++.

Can you reproduce this issue? Any help much appreciated!

```
FAILED: libchrome__combined.so libchrome__combined.so.TOC lib.unstripped/libchrome__combined.so lib.unstripped/libchrome__combined.so.map.gz 
python "../../build/toolchain/gcc_solink_wrapper.py" --readelf="../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-readelf" --nm="../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-nm" --strip=../../buildtools/third_party/eu-strip/bin/eu-strip --sofile="./lib.unstripped/libchrome__combined.so" --tocfile="./libchrome__combined.so.TOC" --map-file "./lib.unstripped/libchrome__combined.so.map.gz" --output="./libchrome__combined.so" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-soname="libchrome__combined.so" -Wl,--version-script=gen/chrome/android/libchrome_linker_script.txt -Wl,--hash-style=gnu -Wl,-soname,libchrome.so --link-only -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -flto=thin -Wl,--thinlto-jobs=8 -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=10g:cache_size_files=100000 -Wl,--lto-O2 -Wl,-mllvm -Wl,-import-instr-limit=5 -Wl,--no-rosegment -Wl,--exclude-libs=libgcc.a -Wl,--exclude-libs=libvpx_assembly_arm.a --target=i686-linux-android16 -m32 -Werror -Wl,--warn-shared-textrel -Wl,-O2 -Wl,--gc-sections -nostdlib++ --sysroot=../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -B../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64 -Wl,--warn-shared-textrel -Wl,--pack-dyn-relocs=android -Wl,-wrap,calloc -Wl,-wrap,free -Wl,-wrap,malloc -Wl,-wrap,memalign -Wl,-wrap,posix_memalign -Wl,-wrap,pvalloc -Wl,-wrap,realloc -Wl,-wrap,valloc -Wl,--dynamic-linker,/system/bin/linker -o "./lib.unstripped/libchrome__combined.so" @"./libchrome__combined.so.rsp"
ld.lld: error: undefined symbol: Java_J_N_Mg_00024zR0Px
>>> referenced by chrome_entry_point.cc
>>>               thinlto-cache/llvmcache-06FDAB5702E4F8E1D1CAA1686FA60FB94AC91446:(kMethods_J_N)

ld.lld: error: undefined symbol: Java_J_N_MWJZTkWR
>>> referenced by chrome_entry_point.cc
>>>               thinlto-cache/llvmcache-06FDAB5702E4F8E1D1CAA1686FA60FB94AC91446:(kMethods_J_N)

ld.lld: error: undefined symbol: Java_J_N_MjGeUNkF
>>> referenced by chrome_entry_point.cc
>>>               thinlto-cache/llvmcache-06FDAB5702E4F8E1D1CAA1686FA60FB94AC91446:(kMethods_J_N)

ld.lld: error: undefined symbol: Java_J_N_Mp340wGB
>>> referenced by chrome_entry_point.cc
>>>               thinlto-cache/llvmcache-06FDAB5702E4F8E1D1CAA1686FA60FB94AC91446:(kMethods_J_N)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

### CODE REVIEW

**Comment by wchen342** [comment]
If it's JNI then it's a native method called from Java. I have seen a similar problem before and what I did is just remove the Java call since it's not used anywhere else. To find out the real name of the method you need to build with `symbol_level=1` and `blink_symbol_level=1` and probably also `is_debug=true`.

**Comment by csagan5** [comment]
@wchen342 thanks; I do remember using `is_debug` in the past to debug this issue. The others are already set to 1, see https://github.com/bromite/bromite/blob/master/build/GN_ARGS

`is_java_debug` will be set by default to the same value as `is_debug`; in this specific case I suspect the call is from native to Java (and not the other way round).

**Comment by wchen342** [comment]
@csagan5 Are you just using the same patches from v79? Cause the main repo hasn't been updated to v80. I can test using the old patches to see whether the same problem will happen in my version.

**Comment by csagan5** [comment]
@wchen342 what do you mean by main repo?

I am using the updated patches as per this PR, which allow building v80. If you use them you will most likely get the same linking error. I have started a new build to see if enabling debug information gives a better linking error, but it's not yet finished.

**Comment by wchen342** [comment]
@csagan5 Sorry I mean Eloston's repo, cause I didn't build with all of your patches in the past I do not know whether it is gonna build successfully. I will give it a try once I get to my machine.

**Comment by csagan5** [comment]
@wchen342 yeah I am publishing Bromite's ones here also to help others, some ungoogled-chromium patches are also used here.

> cause I didn't build with all of your patches in the past I do not know whether it is gonna build successfully
It should if the same GN build flags are used.

I will report back when I have the results of the debug build.

**Comment by nikolowry** [comment]
I'm going to do a debug build now, I'll report back here with my findings.

**Comment by nikolowry** [comment]
I couldn't build with the following GN args, `is_debug=true symbol_level=1 blink_symbol_level=1 is_official_build=false`. I'm more of a scripting guy, so I'm not sure how to resolve the Clang errors those args produced:
```
clang++: error: invalid argument '-fsanitize=cfi-vcall' only allowed with '-flto'
```

My compilation without those flags is currently at 18552/44352 (they totally killed jumbo builds too). Will edit this or add a new comment when I have an update -- which could be the morning, it's late here (NYC)

**Comment by nikolowry** [comment]
I can replicate the error, fairly positive it has to do with this commit https://chromium.googlesource.com/chromium/src.git/+/f72e1a1420c135cf3bf7913ac1a5ad39cb507134

**Comment by csagan5** [comment]
> `clang++: error: invalid argument '-fsanitize=cfi-vcall' only allowed with '-flto'`

I also stepped on this few hours ago; it needs an additional `is_cfi=false` for debug builds.

**Comment by csagan5** [comment]
> I can replicate the error, fairly positive it has to do with this commit https://chromium.googlesource.com/chromium/src.git/+/f72e1a1420c135cf3bf7913ac1a5ad39cb507134

Interesting; how do you associate with that? Chromium builds are fine so it must be some Bromite patch. I also concluded that it is a call from native to Java; perhaps some Bromite patch is doing something wrong with the method declarations (bookmarks etc).

**Comment by nikolowry** [comment]
@csagan5 that was a bad reference -- will investigate tomorrow. Thanks for the `is_cfi` heads up

**Comment by wchen342** [comment]
I was running into a different error
```
[33981/44250] LINK clang_x64/make_top_domain_list_variables
FAILED: clang_x64/make_top_domain_list_variables 
../../../../../../../usr/bin/clang++ -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--color-diagnostics -m64 -Werror -rdynamic -nostdlib++ -pie -Wl,--disable-new-dtags -o "clang_x64/make_top_domain_list_variables" -Wl,--start-group @"clang_x64/make_top_domain_list_variables.rsp"  -Wl,--end-group  -ldl -lpthread -lrt -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0 -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lresolv -lgio-2.0 -latomic -lm -lz -lX11 -lXcomposite -lXdamage -lXext -lXfixes -lXrender
ld.lld: error: undefined symbol: DeblockingBSCalcEnc_neon
>>> referenced by deblocking.cpp:558 (../../third_party/openh264/src/codec/encoder/core/src/deblocking.cpp:558)
>>>               clang_x64/obj/third_party/openh264/encoder/deblocking.o:(WelsEnc::DeblockingBSCalc_neon(WelsEnc::TagWelsFuncPointerList*, WelsEnc::TagMB*, unsigned char (*) [4][4], unsigned int, int, int, int))

ld.lld: error: undefined symbol: WelsNonZeroCount_neon
>>> referenced by deblocking.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/deblocking.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/deblocking.o:(WelsEnc::WelsBlockFuncInit(void (**)(signed char*), int))

ld.lld: error: undefined symbol: DeblockChromaEq4H_neon
>>> referenced by deblocking.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/deblocking.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/deblocking.o:(WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int))

ld.lld: error: undefined symbol: DeblockChromaLt4H_neon
>>> referenced by deblocking.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/deblocking.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/deblocking.o:(WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int))

ld.lld: error: undefined symbol: DeblockChromaEq4V_neon
>>> referenced by deblocking.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/deblocking.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/deblocking.o:(WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int))

ld.lld: error: undefined symbol: DeblockChromaLt4V_neon
>>> referenced by deblocking.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/deblocking.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/deblocking.o:(WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int))

ld.lld: error: undefined symbol: DeblockLumaEq4H_neon
>>> referenced by deblocking.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/deblocking.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/deblocking.o:(WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int))

ld.lld: error: undefined symbol: DeblockLumaLt4H_neon
>>> referenced by deblocking.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/deblocking.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/deblocking.o:(WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int))

ld.lld: error: undefined symbol: DeblockLumaEq4V_neon
>>> referenced by deblocking.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/deblocking.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/deblocking.o:(WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int))

ld.lld: error: undefined symbol: DeblockLumaLt4V_neon
>>> referenced by deblocking.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/deblocking.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/deblocking.o:(WelsEnc::DeblockingInit(WelsEnc::tagDeblockingFunc*, int))

ld.lld: error: undefined symbol: WelsIDctRecI16x16Dc_neon
>>> referenced by decode_mb_aux.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/decode_mb_aux.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/decode_mb_aux.o:(WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int))

ld.lld: error: undefined symbol: WelsIDctT4Rec_neon
>>> referenced by decode_mb_aux.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/decode_mb_aux.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/decode_mb_aux.o:(WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int))

ld.lld: error: undefined symbol: WelsIDctFourT4Rec_neon
>>> referenced by decode_mb_aux.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/decode_mb_aux.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/decode_mb_aux.o:(WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int))

ld.lld: error: undefined symbol: WelsDequantIHadamard4x4_neon
>>> referenced by decode_mb_aux.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/decode_mb_aux.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/decode_mb_aux.o:(WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int))

ld.lld: error: undefined symbol: WelsDequantFour4x4_neon
>>> referenced by decode_mb_aux.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/decode_mb_aux.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/decode_mb_aux.o:(WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int))

ld.lld: error: undefined symbol: WelsDequant4x4_neon
>>> referenced by decode_mb_aux.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/decode_mb_aux.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/decode_mb_aux.o:(WelsEnc::WelsInitReconstructionFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int))

ld.lld: error: undefined symbol: WelsHadamardQuant2x2SkipKernel_neon
>>> referenced by encode_mb_aux.cpp:455 (../../third_party/openh264/src/codec/encoder/core/src/encode_mb_aux.cpp:455)
>>>               clang_x64/obj/third_party/openh264/encoder/encode_mb_aux.o:(WelsHadamardQuant2x2Skip_neon)

ld.lld: error: undefined symbol: WelsDctFourT4_neon
>>> referenced by encode_mb_aux.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/encode_mb_aux.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/encode_mb_aux.o:(WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int))

ld.lld: error: undefined symbol: WelsCopy16x8NotAligned_neon
>>> referenced by encode_mb_aux.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/encode_mb_aux.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/encode_mb_aux.o:(WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int))

ld.lld: error: undefined symbol: WelsCopy16x16NotAligned_neon
>>> referenced by encode_mb_aux.cpp:0 (../../third_party/openh264/src/codec/encoder/core/src/encode_mb_aux.cpp:0)
>>>               clang_x64/obj/third_party/openh264/encoder/encode_mb_aux.o:(WelsEnc::WelsInitEncodingFuncs(WelsEnc::TagWelsFuncPointerList*, unsigned int))

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried to set `use_openh264=false` but I'm still getting this error. Any idea why this is happening?

**Comment by nikolowry** [comment]
@csagan5 just woke up to my debug build with the same error -- I'll let you know if I find any solution

**Comment by csagan5** [comment]
> I tried to set `use_openh264=false` but I'm still getting this error. Any idea why this is happening?

@wchen342 I am getting the same error when building `arm64` (plus another error `fatal error: 'sys/cdefs.h' file not found` which I think it's due to broken `bionic` support, `xenial` must be used to build even they say both are supported).

Since building Chromium alone works successfully, I think this is due to this patch: https://github.com/bromite/bromite/blob/master/build/patches/openH264-enable-ARM-ARM64-optimizations.patch

**Comment by csagan5** [comment]
@wchen342 I have updated the patch here to fix the openH264 error; after about two years it is no more possible to use Neon optimizations on arm64.

@nikolowry finally, the non-mangled errors are these:
```
FAILED: libchrome__combined.so libchrome__combined.so.TOC lib.unstripped/libchrome__combined.so 
python "../../build/toolchain/gcc_solink_wrapper.py" --readelf="../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-readelf" --nm="../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm" --strip=../../buildtools/third_party/eu-strip/bin/eu-strip --sofile="./lib.unstripped/libchrome__combined.so" --tocfile="./libchrome__combined.so.TOC" --output="./libchrome__combined.so" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-soname="libchrome__combined.so" -Wl,--version-script=gen/chrome/android/libchrome_linker_script.txt -Wl,--hash-style=gnu -Wl,-soname,libchrome.so --link-only -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,-z,max-page-size=4096 -Wl,--color-diagnostics -Wl,--no-rosegment -Wl,--exclude-libs=libgcc.a -Wl,--exclude-libs=libvpx_assembly_arm.a --target=aarch64-linux-android21 -Wl,-mllvm,-enable-machine-outliner=never -Werror -nostdlib++ --sysroot=../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -B../../third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64 -Wl,--warn-shared-textrel -Wl,--pack-dyn-relocs=android -Wl,-wrap,calloc -Wl,-wrap,free -Wl,-wrap,malloc -Wl,-wrap,memalign -Wl,-wrap,posix_memalign -Wl,-wrap,pvalloc -Wl,-wrap,realloc -Wl,-wrap,valloc -Wl,--dynamic-linker,/system/bin/linker64 -o "./lib.unstripped/libchrome__combined.so" @"./libchrome__combined.so.rsp"
ld.lld: error: undefined symbol: Java_org_chromium_base_natives_GEN_1JNI_org_1chromium_1chrome_1browser_1safe_11browsing_1SafeBrowsingBridge_1umaValueForFile
>>> referenced by chrome_entry_point.cc
>>>               obj/chrome/android/libchrome__combined/chrome_entry_point.o:(kMethods_org_chromium_base_natives_GEN_1JNI)

ld.lld: error: undefined symbol: Java_org_chromium_base_natives_GEN_1JNI_org_1chromium_1chrome_1browser_1safe_11browsing_1SafeBrowsingBridge_1getSafeBrowsingExtendedReportingEnabled
>>> referenced by chrome_entry_point.cc
>>>               obj/chrome/android/libchrome__combined/chrome_entry_point.o:(kMethods_org_chromium_base_natives_GEN_1JNI)

ld.lld: error: undefined symbol: Java_org_chromium_base_natives_GEN_1JNI_org_1chromium_1chrome_1browser_1safe_11browsing_1SafeBrowsingBridge_1setSafeBrowsingExtendedReportingEnabled
>>> referenced by chrome_entry_point.cc
>>>               obj/chrome/android/libchrome__combined/chrome_entry_point.o:(kMethods_org_chromium_base_natives_GEN_1JNI)

ld.lld: error: undefined symbol: Java_org_chromium_base_natives_GEN_1JNI_org_1chromium_1chrome_1browser_1safe_11browsing_1SafeBrowsingBridge_1getSafeBrowsingExtendedReportingManaged
>>> referenced by chrome_entry_point.cc
>>>               obj/chrome/android/libchrome__combined/chrome_entry_point.o:(kMethods_org_chromium_base_natives_GEN_1JNI)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

They are safe-browsing related, I am going to work on a fix.

**Comment by wchen342** [comment]
Yeah I just finished my build and saw that. That's the exact same problem I faced before. I have a patch [here](https://github.com/wchen342/ungoogled-chromium-android/blob/master/patches/src-fix/fix-extra-safe-browsing.patch).

**Comment by csagan5** [comment]
@wchen342 I have also fixed it and will update the patches here. Now I am fixing some crashes.

**Comment by wchen342** [comment]
@csagan5 Good to know. Let me know when it is ready.

**Comment by csagan5** [comment]
@wchen342 I have updated them here; at least now it builds correctly, but there is still at least one crash to address.

**Comment by csagan5** [comment]
The `fatal error: 'sys/cdefs.h' file not found` persists but only comes up for the SystemWebView; I do not have an idea of the reason so far. All necessary libc dependencies should be already installed by the install-deps scripts.

**Comment by csagan5** [comment]
@wchen342 it should now be crash-free; there's still the `fatal error: 'sys/cdefs.h' file not found` which prevents SystemWebView from being built.

**Comment by nikolowry** [comment]
@csagan5 I typically only build the arm64 variant of `chrome_modern_public_apk` unless you or someone else requests otherwise -- so that wasn't issue for me.

I'm going to SSH into my DO droplet this weekend and try to a manual build first. I'll post back my findings after that

**Comment by csagan5** [comment]
I have figured out that the `cdefs.h` include error only happens for `SystemWebView` with `is_debug=false`.

**Comment by csagan5** [comment]
Thanks all for the assistance! I am merging this.

**Comment by nikolowry** [comment]
Everything built well and is running smoothly with the new release, thanks for being so proactive with updating patches @csagan5. Apologizes again for that bad attribution, I shouldn't debug in a fatigued state.

**Comment by csagan5** [comment]
> Apologizes again for that bad attribution

No need to apologise; I asked for clues to investigate in all directions.

> running smoothly

There are still some crash issues but I will work on a fix for next release.

**Comment by nikolowry** [comment]
> There are still some crash issues but I will work on a fix for next release.

I haven't had a single issue with my arm64 Chrome Modern Public build running on Lineage 16 w MicroG. Don't hesitate to @ me if you need me

**Comment by csagan5** [comment]
See #484

**Pull request merged**
