### PR TITLE
Add a flag (default enabled) for "Ignore enterprise policies for secure DNS" patch

### PR DESCRIPTION
**Pull request by uazo**
as anticipated https://github.com/bromite/bromite/issues/941#issuecomment-783665701
it is probably best to always add a flag to each patch

### CODE REVIEW

**Comment by csagan5** [comment]
It is probably a good idea, ungoogled-chromium already does this, but I am not convinced we need to introduce this now for this feature.

**Comment by uazo** [comment]
you see, for me it is useful in case of troubleshooting, and it doesn't hurt.
rejects the pr if you want.

**Comment by csagan5** [comment]
I look at it from the perspective of extra patch maintenance and because of all the other features/changes that do not have it.

If we want to merge this we should probably invert it? e.g. `kEnableDeviceEnterpriseInfo` by default disabled

**Comment by uazo** [comment]
> I look at it from the perspective of extra patch maintenance and because of all the other features/changes that do not have it.

I'm slowly reviewing all the patches, it's a bit long as an activity, we might think about adding them the first time we touch them.

> e.g. kEnableDeviceEnterpriseInfo by default disabled

sure

**Comment by uazo** [comment]
sorry for the long wait! I'm cleaning the various pulls

I inverted the flag...
I moved the patch to the bottom because it was more convenient for me, sorry if this can take you more with the rebase, but I don't think

**Comment by csagan5** [comment]
Thanks for your update, I am still not convinced about this patch for two reasons:

* who would be needing this patch? e.g. some user that has problems because an enterprise policy is not in act: do we have any?
* wouldn't we need a patch like this for any enterprise policy we override?

**Comment by uazo** [comment]
> who would be needing this patch? e.g. some user that has problems because an enterprise policy is not in act: do we have any?

yes, you are right, it makes little sense, if I were an it manager I would hardly propose the use of bromite in the enterprise environment.
leave it as it is now `if(true)`

> wouldn't we need a patch like this for any enterprise policy we override?

no, for the reasons mentioned above.
eventually it would be interesting the kiosk mode with the always unknown (and possibly the block to access the settings) for those who let use the tablet in public places, if any company is interested (and contributed to the project :).

let's close the pr.

**Pull request closed without merging**
