### PR TITLE
Update Add-option-to-use-home-page-as-NTP.patch for v95

### PR DESCRIPTION
**Pull request by uazo**
patch fixed, I added a button to set, if the user wants, the blank page.
I didn't use `UrlConstants.CHROME_BLANK_URL` because it's deprecated and removed a month ago.

### CODE REVIEW

**Comment by csagan5** [comment]
> patch fixed, I added a button to set, if the user wants, the blank page.

I think this is not needed because if you set your home page as blank and then use the home as NTP, you achieved the same result.

**Comment by uazo** [comment]
> I think this is not needed because if you set your home page as blank and then use the home as NTP, you achieved the same result.

yes, that's right, I had noticed. then I saw this [assert](https://source.chromium.org/chromium/chromium/src/+/main:chrome/android/java/src/org/chromium/chrome/browser/metrics/LaunchMetrics.java;l=106;drc=429093c183d9f48446bc5d2dae196fa6d907c9e1) and I got the doubt, in fact I removed it, and it still seems to work, although it would be better defined.

**Comment by csagan5** [comment]
That is about metrics, not important.

**Review by csagan5 — CHANGES_REQUESTED** [review]
Since it is possible to use `about:blank` via the home page it would be best that we make the patch smaller/simpler and remove that (duplicate) capability.

**Comment by uazo** [comment]
>  would be best that we make the patch smaller/simpler

it's already quite small and simple, what do you mean?

> and remove that (duplicate) capability.

sorry I don't understand the request, can you detail it?

**Comment by csagan5** [comment]
> > and remove that (duplicate) capability.
> 
> sorry I don't understand the request, can you detail it?

Please remove `NTP_SET_ABOUT_BLANK`

**Review by csagan5 — APPROVED** [review]

**Pull request merged**
