### PR TITLE
Fix Omnibox flag not working

### LINKED ISSUE #789: Search Ready Omnibox flag not working
### Bromite version

Version: `86.0.4240.112`
Arch: `arm64`
Android version: `9.0`
Device model: `Galaxy S20`

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Describe the bug

Enabling the `Search Ready Omnibox` flag does not work, the feature stays off.

### PR DESCRIPTION
**Pull request by uazo**
fixes #789 as written here

https://github.com/bromite/bromite/issues/565#issuecomment-680679575

tell me if I have misunderstood

### CODE REVIEW

**Comment by csagan5** [comment]
@uazo with this patch does Bromite have no Omnibox by default and after enabling the flag Omnibox is working?

**Review by csagan5 — CHANGES_REQUESTED** [review]
This PR does not fix the Omnibox flag, it makes Omnibox always enabled - regardless of the flag value.

**Comment by uazo** [comment]
https://github.com/bromite/bromite/issues/565#issuecomment-680696966

>> if the purpose is not to "Cleanup Search Ready Omnibox"

>It's a revert of the cleanup.

No, this PR is for that.
Why the need to disable omnibox?

**Comment by csagan5** [comment]
> Why the need to disable omnibox?

The default behaviour is to have Omnibox always enabled; there is a patch in Bromite to allow to disable it. What does this PR do exactly? It does not fix #789. If one wanted Omnibox always enabled then the Bromite patch could simply be dropped.

**Comment by uazo** [comment]
> What does this PR do exactly? 

clear omnibox textbox

with that flag enabled:
image

disabled:
image

also see that buttons to share/copy/edit are active

**Comment by csagan5** [comment]
Ok, that is an improvement, however not a fix for #789

**Comment by uazo** [comment]
I honestly don't understand you.
I may be wrong, but I am referring to

https://github.com/bromite/bromite/issues/350
https://github.com/bromite/bromite/issues/469
https://github.com/bromite/bromite/issues/404

could you explain how you would like to fix it #789 ?

**Comment by csagan5** [comment]
Flag enabled: like Chromium
Flag disabled: like Bromite is now

**Review by csagan5 — APPROVED** [review]

**Comment by csagan5** [comment]
Great job @uazo! Many thanks

**Pull request merged**
